## Acoustic Model

In [29]:
import torch
import torch.functional as F

In [30]:
tinymodel = TinyModel()

print('The model:')
print(tinymodel)

print('\n\nJust one layer:')
print(tinymodel.linear2)

print('\n\nModel params:')
for param in tinymodel.parameters():
    print(param)

print('\n\nLayer params:')
for param in tinymodel.linear2.parameters():
    print(param)

The model:
TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


Just one layer:
Linear(in_features=200, out_features=10, bias=True)


Model params:
Parameter containing:
tensor([[-0.0771,  0.0061, -0.0688,  ..., -0.0180, -0.0530, -0.0145],
        [ 0.0797, -0.0062, -0.0446,  ...,  0.0003, -0.0402, -0.0186],
        [ 0.0258,  0.0019, -0.0545,  ..., -0.0303,  0.0249, -0.0859],
        ...,
        [-0.0183, -0.0084, -0.0307,  ...,  0.0221,  0.0567,  0.0248],
        [ 0.0566, -0.0782, -0.0880,  ...,  0.0740,  0.0555,  0.0436],
        [ 0.0090,  0.0176, -0.0463,  ..., -0.0351,  0.0606, -0.0272]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0888, -0.0859,  0.0678, -0.0913,  0.0073, -0.0020,  0.0551,  0.0239,
        -0.0418,  0.0730,  0.0221, -0.0748,  0.0112, -0.0206, -0.0157,  0.0174,
        -0.0301,  0.0595, -0.0189, -0.01

In [31]:
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print('Input:')
print(x)

print('\n\nWeight and Bias parameters:')
for param in lin.parameters():
    print(param)

y = lin(x)
print('\n\nOutput:')
print(y)

Input:
tensor([[0.1350, 0.3273, 0.7796]])


Weight and Bias parameters:
Parameter containing:
tensor([[ 0.0670, -0.3657,  0.5161],
        [-0.4756,  0.0138,  0.5107]], requires_grad=True)
Parameter containing:
tensor([-0.1759,  0.5461], requires_grad=True)


Output:
tensor([[0.1158, 0.8845]], grad_fn=<AddmmBackward0>)


In [32]:
my_tensor = torch.rand(1, 6, 6)
print(my_tensor)

maxpool_layer = torch.nn.MaxPool2d(3)
print(maxpool_layer(my_tensor))

tensor([[[0.8935, 0.7953, 0.1451, 0.9670, 0.3374, 0.0519],
         [0.4609, 0.9474, 0.4939, 0.2218, 0.0347, 0.7199],
         [0.3204, 0.0617, 0.1562, 0.4121, 0.0531, 0.7541],
         [0.5746, 0.1838, 0.2302, 0.4575, 0.8068, 0.6952],
         [0.8752, 0.6129, 0.3577, 0.7702, 0.5971, 0.9263],
         [0.4368, 0.0402, 0.7675, 0.8193, 0.3880, 0.4241]]])
tensor([[[0.9474, 0.9670],
         [0.8752, 0.9263]]])


In [33]:
my_tensor = torch.rand(1, 4, 4) * 20 + 5
print(my_tensor)

print(my_tensor.mean())

norm_layer = torch.nn.BatchNorm1d(4)
normed_tensor = norm_layer(my_tensor)
print(normed_tensor)

print(normed_tensor.mean())

tensor([[[22.2920,  8.8247, 12.4303, 15.9764],
         [ 9.5832, 13.0983,  9.0266, 10.0989],
         [20.1638, 20.4009, 17.2764,  7.0051],
         [18.2400,  6.0084, 12.7183, 24.6000]]])
tensor(14.2340)
tensor([[[ 1.4911, -1.2185, -0.4931,  0.2204],
         [-0.5517,  1.6811, -0.9052, -0.2241],
         [ 0.7244,  0.7679,  0.1952, -1.6875],
         [ 0.4154, -1.3683, -0.3898,  1.3428]]],
       grad_fn=<NativeBatchNormBackward0>)
tensor(-1.4901e-08, grad_fn=<MeanBackward0>)


In [34]:
my_tensor = torch.rand(1, 4, 4)

dropout = torch.nn.Dropout(p=0.4)
print(dropout(my_tensor))
print(dropout(my_tensor))

tensor([[[0.2348, 0.2091, 1.0445, 0.7846],
         [0.0000, 0.7000, 0.0000, 1.0638],
         [0.4248, 1.4691, 1.6448, 0.0000],
         [1.0528, 0.8208, 1.6170, 1.4602]]])
tensor([[[0.2348, 0.2091, 1.0445, 0.0000],
         [0.2724, 0.0000, 0.0000, 1.0638],
         [0.4248, 1.4691, 0.0000, 0.0000],
         [1.0528, 0.0000, 1.6170, 0.0000]]])
